version: '3.1'
services:
  db: #this name is used to mention the server name
    image: postgres #pull the image of the db we want to make use of it
    restart: always
    #volumes:
    #  - ./docker-data/db-data:/var/lib/postgresql/data #volumes used to match the dabase data in docker to local directory because when it goes down we have backup  
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432 #every database has default port no on which it work
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8090:8080 #localhost:defaulthost